// SiGG-GoLang-On-the-Fly //

//go:build !reference
// +build !reference

package apiserver

import (
	"context"
	"crypto/sha1"
	"fmt"
	"io/ioutil"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"testing"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/hyperledger/firefly-common/pkg/config"
	"github.com/hyperledger/firefly/internal/coreconfig"

	"github.com/stretchr/testify/assert"
)

func TestDiffSwaggerYAML(t *testing.T) {
	coreconfig.Reset()
	config.Set(coreconfig.APIOASPanicOnMissingDescription, true)
	as := &apiServer{}
	hf := as.handlerFactory()
	handler := hf.APIWrapper(as.swaggerHandler(as.swaggerGenerator(routes, "http://localhost:5000")))
	s := httptest.NewServer(http.HandlerFunc(handler))
	defer s.Close()

	res, err := http.Get(fmt.Sprintf("http://%s/api/swagger.yaml", s.Listener.Addr()))
	assert.NoError(t, err)
	assert.Equal(t, 200, res.StatusCode)
	b, _ := ioutil.ReadAll(res.Body)
	doc, err := openapi3.NewLoader().LoadFromData(b)
	assert.NoError(t, err)
	err = doc.Validate(context.Background())
	assert.NoError(t, err)

	actualSwaggerHash := sha1.New()
	actualSwaggerHash.Write(b)

	var existingSwaggerBytes []byte
	existingSwaggerBytes, err = os.ReadFile(filepath.Join("..", "..", "docs", "swagger", "swagger.yaml"))
	assert.NoError(t, err)

	expectedSwaggerHash := sha1.New()
	expectedSwaggerHash.Write(existingSwaggerBytes)

	assert.Equal(t, actualSwaggerHash.Sum(nil), expectedSwaggerHash.Sum(nil), "The swagger generated by the code did not match the swagger.yml file in git. Did you forget to run `make reference`?")
}
